name: ReferFriend
main: co.mccn.referfriend.ReferFriend
version: ${project.version}
depend: [MCCNSQL, TokenAPI]
commands:
  referredby:
    description: Access Refer a Friend Commands
    usage: Syntax error! Command is /referredby [player]